services:
  - type: web
    name: safeena-birthday
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_CODE
        sync: false

      - key: CHAT_USER1_EMAIL
        sync: false
      - key: CHAT_USER1_PASSWORD
        sync: false
      - key: CHAT_USER1_NAME
        sync: false
      - key: CHAT_USER2_EMAIL
        sync: false
      - key: CHAT_USER2_PASSWORD
        sync: false
      - key: CHAT_USER2_NAME
        sync: false

